name: Deploy Angular app to Azure Web App - paramours

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F607A196A5C04F0CAA27B58E99A30BB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E89EF8F83B16407EBA698506BFB1CD7E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_731B4E04158545B3ABD273255954425A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'paramours'
          slot-name: 'Production'
          package: dist/cl.app.paramours
          startup-command: node server/server.mjs
